config/routes.rb
OrderSamplex::Engine.routes.draw do
  resources :samples
  
  root :to => 'samples#index'

end

app/models/order_samplex/sample.rb
module OrderSamplex
  class Sample < ActiveRecord::Base
    attr_accessor :oked_noupdate
    attr_accessible :delivery_date, :oked, :oked_date, :order_id, :qty, :quality_feedback, :sample_requirement, :shipping_date, 
                    :shipping_instruction, :shipping_tracking, :last_updated_by_id,
                    :as => :role_new
    attr_accessible :delivery_date, :oked, :oked_date, :order_id, :qty, :quality_feedback, :sample_requirement, :shipping_date, 
                    :shipping_instruction, :shipping_tracking,
                    :oked_noupdate,
                    :as => :role_update
    belongs_to :last_updated_by, :class_name => 'Authentify::User'
    belongs_to :order, :class_name => OrderSamplex.order_class.to_s
    
    validates :order_id, :presence => true,
                         :numericality => {:greater_than => 0}
    validates :qty, :presence => true,
                    :numericality => {:greater_than => 0, :message => I18n.t('Qty > 0')}                     
    validates_presence_of :delivery_date                
  end
end

app/controllers/order_samplex/application_controller.rb
module OrderSamplex
  class ApplicationController < ApplicationController
    include Authentify::SessionsHelper
    include Authentify::AuthentifyUtility
    include Authentify::UsersHelper
    include Authentify::UserPrivilegeHelper
    include Commonx::CommonxHelper
    
    before_filter :require_signin
    before_filter :max_pagination
    before_filter :check_access_right 
    before_filter :load_session_variable, :only => [:new, :edit]  #for parent_record_id & parent_resource in check_access_right
    after_filter :delete_session_variable, :only => [:create, :update]  #for parent_record_id & parent_resource in check_access_right
    before_filter :view_in_config?
    
    protected
  
    def max_pagination
      @max_pagination = find_config_const('pagination')
    end
    
    def view_in_config?
      @view_in_config = Authentify::AuthentifyUtility.load_view_in_config
    end
  end
end

app/controllers/order_samplex/samples_controller.rb
require_dependency "order_samplex/application_controller"

module OrderSamplex
  class SamplesController < ApplicationController
    before_filter :require_employee
    before_filter :load_parent_record
    
    def index
      @title = t('Samples')
      @samples = params[:order_samplex_samples][:model_ar_r]
      @samples = @samples.where(:order_id => @order.id) if @order
      @samples = @samples.page(params[:page]).per_page(@max_pagination)
      @erb_code = find_config_const('sample_index_view', 'order_samplex')
    end
  
    def new
      @title = t('New Sample')
      @sample = OrderSamplex::Sample.new()
      @erb_code = find_config_const('sample_new_view', 'order_samplex')
    end
  
    def create
      @sample = OrderSamplex::Sample.new(params[:sample], :as => :role_new)
      @sample.last_updated_by_id = session[:user_id]
      if @sample.save
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Saved!")
      else
        @order = OrderSamplex.order_class.find_by_id(params[:sample][:order_id]) if params[:sample].present? && params[:sample][:order_id].present?
        @erb_code = find_config_const('sample_new_view', 'order_samplex')
        flash[:notice] = t('Data Error. Not Saved!')
        render 'new'
      end
    end
  
    def edit
      @title = t('Update Sample')
      @sample = OrderSamplex::Sample.find_by_id(params[:id])
      @erb_code = find_config_const('sample_edit_view', 'order_samplex')
    end
  
    def update
      @sample = OrderSamplex::Sample.find_by_id(params[:id])
      @sample.last_updated_by_id = session[:user_id]
      if @sample.update_attributes(params[:sample], :as => :role_update)
        redirect_to URI.escape(SUBURI + "/authentify/view_handler?index=0&msg=Successfully Updated!")
      else
        @erb_code = find_config_const('sample_edit_view', 'order_samplex')
        flash[:notice] = t('Data Error. Not Updated!')
        render 'edit'
      end
    end
  
    def show
      @title = t('Sample Info')
      @sample = OrderSamplex::Sample.find_by_id(params[:id])
      @erb_code = find_config_const('sample_show_view', 'order_samplex')
    end
    
    protected
    def load_parent_record
      @order = OrderSamplex.order_class.find_by_id(params[:order_id]) if params[:order_id].present?
      @order = OrderSamplex.order_class.find_by_id(OrderSamplex::Sample.find_by_id(params[:id]).order_id) if params[:id]
    end
  end
end

app/helpers/order_samplex/application_helper.rb
module OrderSamplex
  module ApplicationHelper
  end
end

app/helpers/order_samplex/samples_helper.rb
module OrderSamplex
  module SamplesHelper
  end
end

app/views/order_samplex/samples/_form.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<%= simple_form_for @sample do |f| %>    

  <%= f.input :order_id, :label => t("Order#"), :readonly => true, :input_html => {:value => @order.id} %> 
  <%= f.input :qty, :label => t("Qty") %>
  <%= f.input :sample_requirement, :label => t("Sample Requirement"), :input_html => {:rows => 2} unless readonly?(@sample, 'sample_requirement')%>   
  <%= f.input :sample_requirement, :label => t("Sample Requirement"), :readonly => true, :input_html => {:rows => 2} if readonly?(@sample, 'sample_requirement')%>
  <%= f.input :delivery_date, :label => t("Delivery Date"), :as => :string %>
  <%= f.input :shipping_tracking, :label => t("Shipping Tracking") %>  
  <%= f.input :shipping_date, :label => t("Shipping Date"), :as => :string %> 
  <%= f.input :shipping_instruction, :label => t("Shipping Instruction"), :input_html => {:rows => 2} %> 
  <%= f.input :quality_feedback, :label => t('Quality Feedback'), :input_html => {:rows => 2} unless readonly?(@sample, 'quality_feedback') %>
  <%= f.input :quality_feedback, :label => t('Quality Feedback'), :readonly => true, :input_html => {:rows => 2} if readonly?(@sample, 'quality_feedback') %>
  <% if readonly?(@sample, 'oked')%>
     <%= f.input :oked_noupdate, :label => t('Sample Passed'), :readonly => true, :required => false, :input_html => {:value => @sample.oked} %>
  <% else %>
     <%= f.input :oked, :label => t('Sample Passed'), :as => :boolean %>
  <% end %>
  <%= f.input :oked_date, :label => t("Date Passed"), :as => :string %> 
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save') %>  
<% end %>

<% end %>

app/views/order_samplex/samples/_form_list.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<div class="pagination"><%= will_paginate models %></div>
    <table class="table table-striped">
		<tr>
			<th>#</th>
			<th><%= t('Order#') %></th>
			<th><%= t('Sample Requirement') %></th>
			<th><%= t('Qty') %></th>	
			<th><%= t('Delivery Date') %></th>			
			<th><%= t('Shipping Tracking') %></th>			
			<th><%= t('Shipping Date') %></th>
			<th><%= t('Passed?') %></th>
			<th><%= t('Last Updated By') %></th>
			<th></th>
			
		</tr>
		<% models.each do |r| %>
		  <tr>
		  	<td><%= link_to r.id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{sample_path(r)}" %></td>
		  	<% unless has_action_right?('show', OrderSamplex.order_class.to_s.underscore, r) %>
		  	  <td><%= r.order_id %></td>
		  	<% else %>
		  	  <td><%= link_to r.order_id.to_s, SUBURI + "/authentify/view_handler?index=1&url=#{eval(OrderSamplex.show_order_path)}" %></td>
		  	<% end %>
		  	<td><%= r.sample_requirement %></td>
		  	<td><%= prt(r, :qty) %></td>
			<td><%= r.delivery_date.strftime("%Y/%m/%d") %></td>
			<td><%= r.shipping_tracking %></td>
			<td><%= r.shipping_date.strftime("%Y/%m/%d") %></td> 
			<td><%= r.oked ? t('Yes') : t('No') %></td>
			<td><%= prt(r, 'last_updated_by.name') %></td>    
			<td><%= link_to t('Edit'), SUBURI + "/authentify/view_handler?index=1&url=#{edit_sample_path(r)}", :class => BUTTONS_CLS['action']  if has_action_right?('update', params[:controller], r) %></td>
			
		  </tr>
		<% end %>
	</table>
	
	<table class="table table-striped">
	  <tr>
	    <th>
	    	&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
	    	<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action']  %>
	    	<%= link_to t('New Sample'), SUBURI + "/authentify/view_handler?index=1&url=#{CGI::escape new_sample_path(:order_id => @order.id, :parent_record_id => @order.id, :parent_resource => OrderSamplex.order_class.to_s.underscore.pluralize) }", :class => BUTTONS_CLS['action']  if @order && has_action_right?('create', params[:controller], @order) %>
	    </th>
	  </tr>
	</table>

<% end %>	

app/views/order_samplex/samples/_form_new.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: @erb_code %>
  
<% else %>
<%= simple_form_for @sample do |f| %>    

  <%= f.input :order_id, :label => t("Order#"), :readonly => true, :input_html => {:value => @order.id} %> 
  <%= f.input :qty, :label => t("Qty") %>
  <%= f.input :sample_requirement, :label => t("Sample Requirement"), :input_html => {:rows => 2} %>   
  <%= f.input :delivery_date, :label => t("Delivery Date"), :as => :string %>
  <%= f.input :shipping_tracking, :label => t("Shipping Tracking") %>  
  <%= f.input :shipping_date, :label => t("Shipping Date"), :as => :string %> 
  <%= f.input :shipping_instruction, :label => t("Shipping Instruction"), :input_html => {:rows => 2} %> 
  <%= f.input :oked, :label => t("Sample Passed?"), :as => :boolean %> 
  
  <%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :class => BUTTONS_CLS['action'] %>
  <%= f.button :submit, t('Save') %>  
<% end %>

<% end %>

app/views/order_samplex/samples/create.html.erb
<h1>Rfqs#create</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/create.html.erb</p>

app/views/order_samplex/samples/edit.html.erb
<div id="main_body">
<h4><%=t('Edit Sample') %></h4>
 
<%= render 'form'  %>
 
</div>
  
 

app/views/order_samplex/samples/index.html.erb
<div id="main_body">
	<h4><%=t('Samples') %></h>
 
	<%= render partial: 'form_list', locals: {models: @samples} %>
 
</div>

app/views/order_samplex/samples/new.html.erb
<div id="main_body">
<h4><%=t('New Sample') %></h4>

<%= render 'form_new' %>

</div>

app/views/order_samplex/samples/show.html.erb
<% if @view_in_config && @erb_code %>
  <%= render inline: ERB.new(@erb_code).result(binding) %>
  
<% else %>
<div id="main_body">
<h4><%=t('Sample Info') %></h4>

<p>
  <b><%= t('Order#') %></b>
  <%= @sample.order_id %>
</p>
<p>
  <b><%= t('Qty')  %></b>
  <%= @sample.qty %>
</p>
<p>
  <b><%= t('Sample Requirement') %></b>
  <%= @sample.sample_requirement %>
</p>
<p>
  <b><%= t('Delivery Date') %></b>
  <%= @sample.delivery_date.strftime("%Y/%m/%d") %>
</p>
<p>
  <b><%= t('Quqality Feedback') %></b>
  <%= @sample.quality_feedback %>
</p>
<p>
  <b><%= t('Shipping Date') %></b>
  <%= @sample.shipping_date.strftime("%Y/%m/%d") if @sample.shipping_date.present? %>
</p>
<p>
  <b><%= t('Shipping Instruction') %></b>
  <%= @sample.shipping_instruction %>
</p>
<p>
  <b><%= t('OKed') %></b>
  <%= @sample.oked ? t('Yes') : t('No') %>
</p>
<p>
  <b><%= t('Last Updated By') %></b>
  <%= @sample.last_updated_by.name %>
</p>
<p>
  <b>LOG：</b>
  <% Commonx::Log.where('resource_id = ? AND resource_name = ?', @sample.id, params[:controller].sub('/', '_')).order("created_at DESC").each do |t| %>
    <li><%= t.created_at.strftime("%Y/%m/%d") %>,&nbsp; <%= t.last_updated_by.name %>,&nbsp; <%= t.log %> </li>
  <% end %>
</p>

  	<table class="table table-striped">
	  <tr>
	    <th>
  			<%= link_to t('Back'), SUBURI + "/authentify/view_handler?index=0", :id => 'close', :class => BUTTONS_CLS['action'] %>
  			&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
			<%= link_to t('New Log'), SUBURI + commonx.new_log_path(:resource_id => @sample.id, :resource_name => params[:controller], :subaction => 'order_sample', :format => :js), :remote => true, 
                          :id => 'new_log_link', :class => BUTTONS_CLS['action'] if has_action_right?('create_order_sample', 'commonx/logs') %> 
          </th>
	  </tr>
	</table>  
	 	
</div>

<% end %>

app/views/order_samplex/samples/update.html.erb
<h1>Rfqs#update</h1>
<p>Find me in app/views/jobshop_rfqx/rfqs/update.html.erb</p>